### ISSUE TITLE
Appears to sometimes handle stemming badly when long matches precede short ones in keyword list.

### ISSUE THREAD

**Issue by HappMacDonald** [BrunoRB/ahocorasick#3]
Test case:
ac = new AhoCorasick(['.com.au','.com']);
ac.search("www.yahoo.com")
console> [ ]

If you change the order then it works fine:
ac = new AhoCorasick(['.com','.com.au'])
ac.search("www.yahoo.com")
console> ... 12, ... ".com" ...

Diagnostically, I see that the "output" part of the AhoCorasick object wrongly lists ".com" at the same final node as ".com.au" when the shorter term is put after the longer one:

console> ...output:
1: []
2: []
3: []
4: []
5: []
6: []
7: (2) [".com.au", ".com"]

**Comment by BrunoRB** [comment]
Yeah, looks like there's a bug ;( I will have a look into it soon.
Thanks for the report!
