### ISSUE TITLE
Open for PR / contributions?

### ISSUE THREAD

**Issue by peterlundberg** [BrunoRB/ahocorasick#7]
Found this library when needing this in a real world situation. Great work and (relatively) well used linked in npm etc.

When benchmarking with our use case this performed well and better than other packages on npm. Did find a few things that can be improved and allows even faster execution with a modern v8.

However, support for ignoreCase and to emit/output more than just the keyword was missing so this was not directly useable.

Would you be open to contributions or a discussion on how to add this to this library so we can contribute back?

**Comment by amosbastian** [comment]
@peterlundberg did you end up implementing these improvements elsewhere?
